name: intl_country_code
description: A flutter package for showing a country code selector. In addition it gives the possibility to select a list of favorites countries, as well as to search using a simple searchbox  
version: 3.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  modal_bottom_sheet: ^2.1.2
  collection: ^1.17.1
  universal_platform: ^1.0.0+1

flutter:
  assets:
    - flags/
    - packages/intl_country_code/i18n/af.json
    - packages/intl_country_code/i18n/am.json
    - packages/intl_country_code/i18n/ha.json
    - packages/intl_country_code/i18n/ku.json
    - packages/intl_country_code/i18n/ml.json
    - packages/intl_country_code/i18n/no.json
    - packages/intl_country_code/i18n/ps.json
    - packages/intl_country_code/i18n/sd.json
    - packages/intl_country_code/i18n/so.json
    - packages/intl_country_code/i18n/sq.json
    - packages/intl_country_code/i18n/ta.json
    - packages/intl_country_code/i18n/tg.json
    - packages/intl_country_code/i18n/tt.json
    - packages/intl_country_code/i18n/ug.json
    - packages/intl_country_code/i18n/ur.json
    - packages/intl_country_code/i18n/vi.json
    - packages/intl_country_code/i18n/ar.json
    - packages/intl_country_code/i18n/az.json
    - packages/intl_country_code/i18n/be.json
    - packages/intl_country_code/i18n/bg.json
    - packages/intl_country_code/i18n/bn.json
    - packages/intl_country_code/i18n/bs.json
    - packages/intl_country_code/i18n/ca.json
    - packages/intl_country_code/i18n/cs.json
    - packages/intl_country_code/i18n/da.json
    - packages/intl_country_code/i18n/de.json
    - packages/intl_country_code/i18n/el.json
    - packages/intl_country_code/i18n/en.json
    - packages/intl_country_code/i18n/es.json
    - packages/intl_country_code/i18n/et.json
    - packages/intl_country_code/i18n/fa.json
    - packages/intl_country_code/i18n/fi.json
    - packages/intl_country_code/i18n/fr.json
    - packages/intl_country_code/i18n/gl.json
    - packages/intl_country_code/i18n/el.json
    - packages/intl_country_code/i18n/he.json
    - packages/intl_country_code/i18n/hi.json
    - packages/intl_country_code/i18n/hr.json
    - packages/intl_country_code/i18n/hu.json
    - packages/intl_country_code/i18n/hy.json
    - packages/intl_country_code/i18n/id.json
    - packages/intl_country_code/i18n/is.json
    - packages/intl_country_code/i18n/it.json
    - packages/intl_country_code/i18n/ja.json
    - packages/intl_country_code/i18n/ka.json
    - packages/intl_country_code/i18n/kk.json
    - packages/intl_country_code/i18n/km.json
    - packages/intl_country_code/i18n/ko.json
    - packages/intl_country_code/i18n/ky.json
    - packages/intl_country_code/i18n/lt.json
    - packages/intl_country_code/i18n/lv.json
    - packages/intl_country_code/i18n/mk.json
    - packages/intl_country_code/i18n/mn.json
    - packages/intl_country_code/i18n/ms.json
    - packages/intl_country_code/i18n/nb.json
    - packages/intl_country_code/i18n/nl.json
    - packages/intl_country_code/i18n/nn.json
    - packages/intl_country_code/i18n/pl.json
    - packages/intl_country_code/i18n/pt.json
    - packages/intl_country_code/i18n/ro.json
    - packages/intl_country_code/i18n/ru.json
    - packages/intl_country_code/i18n/sk.json
    - packages/intl_country_code/i18n/sl.json
    - packages/intl_country_code/i18n/sr.json
    - packages/intl_country_code/i18n/sv.json
    - packages/intl_country_code/i18n/th.json
    - packages/intl_country_code/i18n/tr.json
    - packages/intl_country_code/i18n/uk.json
    - packages/intl_country_code/i18n/uz.json
    - packages/intl_country_code/i18n/zh.json
